// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokerClassLibrary;

namespace Poker.Migrations
{
    [DbContext(typeof(PokerContext))]
    [Migration("20220514145132_changeMoneyType")]
    partial class changeMoneyType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Hebrew_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Poker.DataModel.Pot", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("_money")
                        .HasColumnType("int");

                    b.Property<int>("_roomId")
                        .HasColumnType("int");

                    b.HasKey("_id");

                    b.ToTable("Pots");
                });

            modelBuilder.Entity("PokerClassLibrary.Card", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("_number")
                        .HasColumnType("int");

                    b.Property<int>("_roomId")
                        .HasColumnType("int");

                    b.Property<int>("_type")
                        .HasColumnType("int");

                    b.HasKey("_id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("PokerClassLibrary.Room", b =>
                {
                    b.Property<string>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("_dealerPosition")
                        .HasColumnType("int");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("_pot")
                        .HasColumnType("int");

                    b.Property<int?>("_talkingPosition")
                        .HasColumnType("int");

                    b.HasKey("_id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("PokerClassLibrary.User", b =>
                {
                    b.Property<string>("_username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("userName");

                    b.Property<string>("_connectionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("_isActive")
                        .HasColumnType("bit");

                    b.Property<int>("_money")
                        .HasColumnType("int")
                        .HasColumnName("userMoney");

                    b.Property<int?>("_moneyInTable")
                        .HasColumnType("int");

                    b.Property<string>("_password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("_position")
                        .HasColumnType("smallint");

                    b.Property<string>("_roomId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_username");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
