// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PokerClassLibrary
{
    public partial class Users
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public int? UserMoney { get; set; }
    }
}