// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Poker.DataModel;

#nullable disable

namespace PokerClassLibrary
{
    public partial class PokerContext : DbContext
    {
        public PokerContext()
        {
        }

        public PokerContext(DbContextOptions<PokerContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<Pot> Pots { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Hebrew_CI_AS");

            // Room
            modelBuilder.Entity<Room>(entity =>
            {
                entity.HasKey(e => e._id);

                entity.Property(e => e._id).ValueGeneratedOnAdd() ;

                entity.Property(e => e._name)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            // User
            modelBuilder.Entity<User>(entity =>
            {
                entity.HasKey(e => e._username);

                entity.Property(e => e._username)
                    .HasMaxLength(50)
                    .HasColumnName("userName");

                entity.Property(e => e._password).HasMaxLength(50);

                entity.Property(e => e._money).HasColumnName("userMoney");
            });

            // Pot
            modelBuilder.Entity<Pot>(entity =>
            {
                entity.HasKey(e => e._id);
            });

            // Card
            modelBuilder.Entity<Card>(entity =>
            {
                entity.HasKey(e => e._id);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}