// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PokerClassLibrary
{
    public partial class Room
    {
        public int RoomId { get; set; }
        public string RoomName { get; set; }
        public int? Pot { get; set; }
    }
}