// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PokerClassLibrary
{
    public partial class UserInRoom
    {
        public string Username { get; set; }
        public int RoomId { get; set; }
        public int? MoneyInTable { get; set; }
        public bool? IsActive { get; set; }
        public short? Position { get; set; }

        public virtual Room Room { get; set; }
        public virtual User UsernameNavigation { get; set; }
    }
}