// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PokerClassLibrary
{
    public partial class User
    {
        public string _username { get; set; }
        public string _password { get; set; }
        public double _money { get; set; }
        public string? _connectionId { get; set; }
        public int? _moneyInTable { get; set; }
        public bool? _isActive { get; set; }
        public short? _position { get; set; }
        public int? _roomId { get; set; }
    }
}