// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PokerClassLibrary
{
    public partial class User
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public int Money { get; set; }
        public string? ConnectionId { get; set; }
        public int MoneyInTable { get; set; }
        public int MoneyInTurn { get; set; }
        public bool IsActive { get; set; }
        public bool PlayedThisTurn { get; set; }
        public short Position { get; set; }
        public string? RoomId { get; set; }
        public virtual List<Card> Cards { get; set; }

        public User()
        {
            this.Cards = new List<Card>();
            this.PlayedThisTurn = false;
            this.IsActive = false;
            this.MoneyInTurn = 0;
            this.MoneyInTable = 0;
            this.Money = 1000;
            this.Position = 0;
        }
    }
}