name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run:  dotnet restore Poker/Poker.sln
    - name: Build
      run: dotnet build Poker/Poker.sln --no-restore
    - name: Test
      run: dotnet test Poker/UnitTestsProject/UnitTestsProject.csproj  --verbosity normal